env:
- CGO_ENABLED=0

before:
  hooks:
  - go mod tidy

builds:
- goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
